apiVersion: core.federation.k8s.io/v1alpha1
kind: FederatedService
metadata:
  name: istio-statsd-prom-bridge
  namespace: istio-system
  labels:
    chart: mixer-0.8.0
    release: istio
    istio: statsd-prom-bridge
spec:
  template:
    spec:
      ports:
      - name: statsd-prom
        port: 9102
      - name: statsd-udp
        port: 9125
        protocol: UDP
      selector:
        istio: statsd-prom-bridge
