apiVersion: core.federation.k8s.io/v1alpha1
kind: FederatedService
metadata:
  name: istio-ingressgateway
  namespace: istio-system
  labels:
    chart: ingressgateway-0.8.0
    release: istio
    heritage: Tiller
    istio: ingressgateway
spec:
  template:
    spec:
      # Replace LoadBalancer with NodePort for minikube and other environments that
      # do not use cloud load-balancers.
      type: LoadBalancer
      selector:
        istio: ingressgateway
      ports:
      - name: http
        nodePort: 31380
        port: 80
      - name: https
        nodePort: 31390
        port: 443
      - name: tcp
        nodePort: 31400
        port: 31400
