apiVersion: core.federation.k8s.io/v1alpha1
kind: FederatedService
metadata:
  name: istio-telemetry
  namespace: istio-system
  labels:
    chart: mixer-0.8.0
    release: istio
    istio: mixer
spec:
  template:
    spec:
      ports:
      - name: grpc-mixer
        port: 9091
      - name: grpc-mixer-mtls
        port: 15004
      - name: http-monitoring
        port: 9093
      - name: prometheus
        port: 42422
      selector:
        istio: mixer
        istio-mixer-type: telemetry
