apiVersion: core.federation.k8s.io/v1alpha1
kind: FederatedService
metadata:
  name: istio-egressgateway
  namespace: istio-system
  labels:
    chart: egressgateway-0.8.0
    release: istio
    heritage: Tiller
    istio: egressgateway
spec:
  template:
    spec:
      type: ClusterIP
      selector:
        istio: egressgateway
      ports:
      - name: http
        port: 80
      - name: https
        port: 443
