apiVersion: v1
kind: Pod
metadata:
  namespace: etcd
  labels:
    component: etcd
  name: etcd
spec:
  containers:
  - command:
    - etcd
    - --name=etcd1
    - --listen-peer-urls=http://0.0.0.0:2380
    - --listen-client-urls=http://0.0.0.0:2379
    - --initial-advertise-peer-urls=http://etcd1.etcd.federation-system.svc.daneyon.com:2380
    - --advertise-client-urls=http://etcd1.etcd.federation-system.svc.daneyon.com:2379
    - --discovery=https://discovery.etcd.io/90c100f1ba1a34a8abd4da196fe06df7
    image: k8s.gcr.io/etcd-amd64:3.2.18
    imagePullPolicy: IfNotPresent
    name: etcd1
    env:
      - name: POD_IP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
