apiVersion: generated.federation.k8s.io/v1alpha1
kind: FederatedCustomResourceDefinition
metadata:
  name: logentries.config.istio.io
  labels:
    app: mixer
    package: logentry
    istio: mixer-instance
spec:
  template:
    spec:
      group: config.istio.io
      names:
        kind: logentry
        plural: logentries
        singular: logentry
      scope: Namespaced
      version: v1alpha2
