apiVersion: generated.federation.k8s.io/v1alpha1
kind: FederatedCustomResourceDefinition
metadata:
  name: destinationpolicies.config.istio.io
  labels:
    app: istio-pilot
spec:
  template:
    spec:
      group: config.istio.io
      names:
        kind: DestinationPolicy
        listKind: DestinationPolicyList
        plural: destinationpolicies
        singular: destinationpolicy
      scope: Namespaced
      version: v1alpha2