apiVersion: core.federation.k8s.io/v1alpha1
kind: FederatedService
metadata:
  name: istio-pilot
  namespace: istio-system
  labels:
    app: istio-pilot
    chart: pilot-0.8.0
    release: istio
    heritage: Tiller
spec:
  template:
    spec:
      ports:
      - port: 15003
        name: http-old-discovery # mTLS or non-mTLS depending on auth setting
      - port: 15005
        name: https-discovery # always mTLS
      - port: 15007
        name: http-discovery # always plain-text
      - port: 15010
        name: grpc-xds # direct
      - port: 15011
        name: https-xds # mTLS
      - port: 8080
        name: http-legacy-discovery # direct
      - port: 9093
        name: http-monitoring
      selector:
        istio: pilot
