apiVersion: generated.federation.k8s.io/v1alpha1
kind: FederatedClusterRolePlacement
metadata:
  labels:
    app: ingress
    chart: ingress-0.8.0
    heritage: Tiller
    release: istio
  name: istio-ingress-istio-system
spec:
  clusterNames:
  - cluster2
  - cluster1
