apiVersion: generated.federation.k8s.io/v1alpha1
kind: FederatedClusterRoleBinding
metadata:
  name: prometheus-istio-system
  #namespace: istio-system # In upstream but should not be needed since Cluster role is cluster-scoped
spec:
  template:
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: prometheus-istio-system
    subjects:
    - kind: ServiceAccount
      name: prometheus
      namespace: istio-system
