apiVersion: generated.federation.k8s.io/v1alpha1
kind: FederatedClusterRoleBinding
metadata:
  name: istio-pilot-istio-system
  labels:
    app: istio-pilot
    chart: pilot-0.8.0
    heritage: Tiller
    release: istio
spec:
  template:
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: istio-pilot-istio-system
    subjects:
      - kind: ServiceAccount
        name: istio-pilot-service-account
        namespace: istio-system
