apiVersion: generated.federation.k8s.io/v1alpha1
kind: FederatedClusterRoleBindingPlacement
metadata:
  name: istio-mixer-admin-role-binding-istio-system
  labels:
    app: mixer
    chart: mixer-0.8.0
    heritage: Tiller
    release: istio
spec:
  clusterNames:
  - cluster2
  - cluster1
