apiVersion: generated.federation.k8s.io/v1alpha1
kind: FederatedClusterRoleBinding
metadata:
  name: istio-citadel-istio-system
  labels:
    app: security
    chart: security-0.8.0
    heritage: Tiller
    release: istio
spec:
  template:
    roleRef:
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: istio-citadel-istio-system
      subjects:
        - kind: ServiceAccount
          name: istio-citadel-service-account
          namespace: istio-system
