apiVersion: v1
kind: List
items:
- apiVersion: core.federation.k8s.io/v1alpha1
  kind: FederatedClusterRoleBindingPlacement
  metadata:
    name: test-clusterrolebinding
  spec:
    clusterNames:
    - cluster2
    - cluster1
