apiVersion: generated.federation.k8s.io/v1alpha1
kind: FederatedClusterRoleBinding
metadata:
  name: istio-citadel-istio-system
  #namespace: istio-system
  labels:
    app: security
    chart: security-0.8.0
    heritage: Tiller
    release: istio
spec:
  template:
    rules:
    - apiGroups: [""]
      resources: ["secrets"]
      verbs: ["create", "get", "watch", "list", "update", "delete"]
    - apiGroups: [""]
      resources: ["serviceaccounts"]
      verbs: ["get", "watch", "list"]
    - apiGroups: [""]
      resources: ["services"]
      verbs: ["get", "watch", "list"]
