apiVersion: generated.federation.k8s.io/v1alpha1
kind: FederatedClusterRole
metadata:
  labels:
    app: ingress
    chart: ingress-0.8.0
    heritage: Tiller
    release: istio
  name: istio-ingress-istio-system
spec:
  template:
    rules:
    - apiGroups: ["extensions"]
      resources: ["thirdpartyresources", "ingresses"]
      verbs: ["get", "watch", "list", "update"]
    - apiGroups: [""]
      resources: ["configmaps", "pods", "endpoints", "services"]
      verbs: ["get", "watch", "list"]
