apiVersion: generated.federation.k8s.io/v1alpha1
kind: FederatedClusterRole
metadata:
  name: istio-pilot-istio-system
  #namespace: istio-system
  labels:
    app: istio-pilot
    chart: pilot-0.8.0
    heritage: Tiller
    release: istio
spec:
  template:
    rules:
    - apiGroups: ["config.istio.io"]
      resources: ["*"]
      verbs: ["*"]
    - apiGroups: ["networking.istio.io"]
      resources: ["*"]
      verbs: ["*"]
    - apiGroups: ["authentication.istio.io"]
      resources: ["*"]
      verbs: ["*"]
    - apiGroups: ["apiextensions.k8s.io"]
      resources: ["customresourcedefinitions"]
      verbs: ["*"]
    - apiGroups: ["extensions"]
      resources: ["thirdpartyresources", "thirdpartyresources.extensions", "ingresses", "ingresses/status"]
      verbs: ["*"]
    - apiGroups: [""]
      resources: ["configmaps"]
      verbs: ["create", "get", "list", "watch", "update"]
    - apiGroups: [""]
      resources: ["endpoints", "pods", "services"]
      verbs: ["get", "list", "watch"]
    - apiGroups: [""]
      resources: ["namespaces", "nodes", "secrets"]
      verbs: ["get", "list", "watch"]
