apiVersion: generated.federation.k8s.io/v1alpha1
kind: FederatedClusterRole
metadata:
  name: istio-mixer-post-install-istio-system
  namespace: istio-system
  labels:
    app: mixer
    chart: mixer-0.8.0
    heritage: Tiller
    release: istio
spec:
  template:
    rules:
    - apiGroups: ["config.istio.io"] # istio CRD watcher
      resources: ["*"]
      verbs: ["create", "get", "list", "watch", "patch"]
    - apiGroups: ["networking.istio.io"] # needed to create mixer destination rules
      resources: ["*"]
      verbs: ["*"]
    - apiGroups: ["apiextensions.k8s.io"]
      resources: ["customresourcedefinitions"]
      verbs: ["get", "list", "watch"]
    - apiGroups: [""]
      resources: ["configmaps", "endpoints", "pods", "services", "namespaces", "secrets"]
      verbs: ["get", "list", "watch"]
