apiVersion: generated.federation.k8s.io/v1alpha1
kind: FederatedClusterRolePlacement
metadata:
  name: istio-citadel-istio-system
  #namespace: istio-system
  labels:
    app: security
    chart: security-0.8.0
    heritage: Tiller
    release: istio
spec:
  clusterNames:
  - cluster2
  - cluster1
