apiVersion: generated.federation.k8s.io/v1alpha1
kind: FederatedClusterRolePlacement
metadata:
  name: istio-mixer-post-install-istio-system
  namespace: istio-system
  labels:
    app: mixer
    chart: mixer-0.8.0
    heritage: Tiller
    release: istio
spec:
  clusterNames:
  - cluster2
  - cluster1
