apiVersion: generated.federation.k8s.io/v1alpha1
kind: FederatedMutatingWebhookConfiguration
metadata:
  name: istio-sidecar-injector
  namespace: istio-system
  labels:
    app: istio-sidecar-injector
    chart: sidecarInjectorWebhook-0.8.0
    release: istio
    heritage: Tiller
spec:
  template:
    webhooks:
    - name: sidecar-injector.istio.io
      clientConfig:
        service:
          name: istio-sidecar-injector
          namespace: istio-system
          path: "/inject"
        caBundle: ""
      rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
      failurePolicy: Fail
      namespaceSelector:
        matchLabels:
          istio-injection: enabled
