apiVersion: primitives.federation.k8s.io/v1alpha1
kind: FederatedServiceEntry
metadata:
  name: google
spec:
  template:
    spec:
      hosts:
      - www.google.com
      ports:
      - number: 443
        name: https
        protocol: HTTPS
      resolution: DNS
      location: MESH_EXTERNAL
---
apiVersion: primitives.federation.k8s.io/v1alpha1
kind: FederatedServiceEntryPlacement
metadata:
  name: google
spec:
  clusterNames:
  - cluster1
  - cluster2
---
apiVersion: primitives.federation.k8s.io/v1alpha1
kind: FederatedVirtualService
metadata:
  name: google
spec:
  template:
    spec:
      hosts:
      - www.google.com
      tls:
      - match:
        - port: 443
          sni_hosts:
          - www.google.com
        route:
        - destination:
            host: www.google.com
            port:
              number: 443
          weight: 100
---
apiVersion: primitives.federation.k8s.io/v1alpha1
kind: FederatedVirtualServicePlacement
metadata:
  name: google
spec:
  clusterNames:
  - cluster1
  - cluster2