apiVersion: generated.federation.k8s.io/v1alpha1
kind: FederatedService
metadata:
  name: fluentds.config.istio.io
  labels:
    app: mixer
    package: fluentd
    istio: mixer-adapter
spec:
  template:
    spec:
      group: config.istio.io
      names:
        kind: fluentd
        plural: fluentds
        singular: fluentd
      scope: Namespaced
      version: v1alpha2
