apiVersion: generated.federation.k8s.io/v1alpha1
kind: FederatedCustomResourceDefinition
metadata:
  name: listcheckers.config.istio.io
  labels:
    app: mixer
    package: listchecker
    istio: mixer-adapter
spec:
  template:
    spec:
      group: config.istio.io
      names:
        kind: listchecker
        plural: listcheckers
        singular: listchecker
      scope: Namespaced
      version: v1alpha2
