apiVersion: generated.federation.k8s.io/v1alpha1
kind: FederatedService
metadata:
  name: tracespans.config.istio.io
  labels:
    app: mixer
    package: tracespan
    istio: mixer-instance
spec:
  template:
    spec:
      group: config.istio.io
      names:
        kind: tracespan
        plural: tracespans
        singular: tracespan
      scope: Namespaced
      version: v1alpha2
