apiVersion: generated.federation.k8s.io/v1alpha1
kind: FederatedCustomResourceDefinition
metadata:
  name: circonuses.config.istio.io
  labels:
    app: mixer
    package: circonus
    istio: mixer-adapter
spec:
  template:
    spec:
      group: config.istio.io
      names:
        kind: circonus
        plural: circonuses
        singular: circonus
      scope: Namespaced
      version: v1alpha2
