apiVersion: generated.federation.k8s.io/v1alpha1
kind: FederatedService
metadata:
  name: statsds.config.istio.io
  labels:
    app: mixer
    package: statsd
    istio: mixer-adapter
spec:
  template:
    spec:
      group: config.istio.io
      names:
        kind: statsd
        plural: statsds
        singular: statsd
      scope: Namespaced
      version: v1alpha2
