apiVersion: generated.federation.k8s.io/v1alpha1
kind: FederatedService
metadata:
  name: deniers.config.istio.io
  labels:
    app: mixer
    package: denier
    istio: mixer-adapter
spec:
  template:
    spec:
      group: config.istio.io
      names:
        kind: denier
        plural: deniers
        singular: denier
      scope: Namespaced
      version: v1alpha2
