apiVersion: generated.federation.k8s.io/v1alpha1
kind: FederatedCustomResourceDefinition
metadata:
  name: kuberneteses.config.istio.io
  labels:
    app: mixer
    package: adapter.template.kubernetes
    istio: mixer-instance
spec:
  template:
    spec:
      group: config.istio.io
      names:
        kind: kubernetes
        plural: kuberneteses
        singular: kubernetes
      scope: Namespaced
      version: v1alpha2