apiVersion: generated.federation.k8s.io/v1alpha1
kind: FederatedCustomResourceDefinition
metadata:
  name: listentries.config.istio.io
  labels:
    app: mixer
    package: listentry
    istio: mixer-instance
spec:
  template:
    spec:
      group: config.istio.io
      names:
        kind: listentry
        plural: listentries
        singular: listentry
      scope: Namespaced
      version: v1alpha2