apiVersion: generated.federation.k8s.io/v1alpha1
kind: FederatedCustomResourceDefinition
metadata:
  name: metrics.config.istio.io
  labels:
    app: mixer
    package: metric
    istio: mixer-instance
spec:
  template:
    spec:
      group: config.istio.io
      names:
        kind: metric
        plural: metrics
        singular: metric
      scope: Namespaced
      version: v1alpha2
