apiVersion: generated.federation.k8s.io/v1alpha1
kind: FederatedService
metadata:
  name: stackdrivers.config.istio.io
  labels:
    app: mixer
    package: stackdriver
    istio: mixer-adapter
spec:
  template:
    spec:
      group: config.istio.io
      names:
        kind: stackdriver
        plural: stackdrivers
        singular: stackdriver
      scope: Namespaced
      version: v1alpha2
