apiVersion: generated.federation.k8s.io/v1alpha1
kind: FederatedService
metadata:
  name: memquotas.config.istio.io
  labels:
    app: mixer
    package: memquota
    istio: mixer-adapter
spec:
  template:
    spec:
      group: config.istio.io
      names:
        kind: memquota
        plural: memquotas
        singular: memquota
      scope: Namespaced
      version: v1alpha2
