apiVersion: generated.federation.k8s.io/v1alpha1
kind: FederatedServicePlacement
metadata:
  name: egressrules.config.istio.io
  labels:
    app: istio-pilot
spec:
  clusterNames:
  - cluster2
  - cluster1
