apiVersion: generated.federation.k8s.io/v1alpha1
kind: FederatedService
metadata:
  name: noops.config.istio.io
  labels:
    app: mixer
    package: noop
    istio: mixer-adapter
spec:
  template:
    spec:
      group: config.istio.io
      names:
        kind: noop
        plural: noops
        singular: noop
      scope: Namespaced
      version: v1alpha2
