apiVersion: generated.federation.k8s.io/v1alpha1
kind: FederatedService
metadata:
  name: virtualservices.networking.istio.io
  labels:
    app: istio-pilot
spec:
  template:
    spec:
      group: networking.istio.io
      names:
        kind: VirtualService
        listKind: VirtualServiceList
        plural: virtualservices
        singular: virtualservice
      scope: Namespaced
      version: v1alpha3