apiVersion: generated.federation.k8s.io/v1alpha1
kind: FederatedServicePlacement
metadata:
  name: apikeys.config.istio.io
  labels:
    app: mixer
    package: apikey
    istio: mixer-instance
spec:
  clusternames:
  - cluster2
  - cluster1
