apiVersion: generated.federation.k8s.io/v1alpha1
kind: FederatedCustomResourceDefinition
metadata:
  name: quotas.config.istio.io
  labels:
    app: mixer
    package: quota
    istio: mixer-instance
spec:
  template:
    spec:
      group: config.istio.io
      names:
        kind: quota
        plural: quotas
        singular: quota
      scope: Namespaced
      version: v1alpha2
