apiVersion: generated.federation.k8s.io/v1alpha1
kind: FederatedCustomResourceDefinition
metadata:
  name: httpapispecbindings.config.istio.io
spec:
  template:
    spec:
      group: config.istio.io
      names:
        kind: HTTPAPISpecBinding
        plural: httpapispecbindings
        singular: httpapispecbinding
      scope: Namespaced
      version: v1alpha2
