apiVersion: generated.federation.k8s.io/v1alpha1
kind: FederatedCustomResourceDefinitionPlacement
metadata:
  name: servicerolebindings.config.istio.io
  labels:
    app: mixer
    package: istio.io.mixer
    istio: rbac
spec:
  clusterNames:
  - cluster2
  - cluster1
