apiVersion: generated.federation.k8s.io/v1alpha1
kind: FederatedService
metadata:
  name: stdios.config.istio.io
  labels:
    app: mixer
    package: stdio
    istio: mixer-adapter
spec:
  template:
    spec:
      group: config.istio.io
      names:
        kind: stdio
        plural: stdios
        singular: stdio
      scope: Namespaced
      version: v1alpha2
