apiVersion: generated.federation.k8s.io/v1alpha1
kind: FederatedServicePlacement
metadata:
  name: listentries.config.istio.io
  labels:
    app: mixer
    package: listentry
    istio: mixer-instance
spec:
  clusterNames:
  - cluster2
  - cluster1
