apiVersion: generated.federation.k8s.io/v1alpha1
kind: FederatedCustomResourceDefinitionPlacement
metadata:
  name: authorizations.config.istio.io
  labels:
    app: mixer
    package: authorization
    istio: mixer-instance
spec:
  clusterNames:
  - cluster2
  - cluster1
