apiVersion: generated.federation.k8s.io/v1alpha1
kind: FederatedService
metadata:
  name: gateways.networking.istio.io
  labels:
    app: istio-pilot
spec:
  template:
    spec:
      group: networking.istio.io
      names:
        kind: Gateway
        plural: gateways
        singular: gateway
      scope: Namespaced
      version: v1alpha3
