apiVersion: generated.federation.k8s.io/v1alpha1
kind: FederatedService
metadata:
  name: attributemanifests.config.istio.io
  labels:
    app: mixer
    package: istio.io.mixer
    istio: core
spec:
  template:
    spec:
      group: config.istio.io
      names:
        kind: attributemanifest
        plural: attributemanifests
        singular: attributemanifest
      scope: Namespaced
      version: v1alpha2
