apiVersion: generated.federation.k8s.io/v1alpha1
kind: FederatedCustomResourceDefinitionPlacement
metadata:
  name: memquotas.config.istio.io
  labels:
    app: mixer
    package: memquota
    istio: mixer-adapter
spec:
  clusterNames:
  - cluster2
  - cluster1
