apiVersion: generated.federation.k8s.io/v1alpha1
kind: FederatedService
metadata:
  name: rbacs.config.istio.io
  labels:
    app: mixer
    package: rbac
    istio: mixer-adapter
spec:
  template:
    spec:
      group: config.istio.io
      names:
        kind: rbac
        plural: rbacs
        singular: rbac
      scope: Namespaced
      version: v1alpha2
