apiVersion: generated.federation.k8s.io/v1alpha1
kind: FederatedService
metadata:
  name: solarwindses.config.istio.io
  labels:
    app: mixer
    package: solarwinds
    istio: mixer-adapter
spec:
  template:
    spec:
      group: config.istio.io
      names:
        kind: solarwinds
        plural: solarwindses
        singular: solarwinds
      scope: Namespaced
      version: v1alpha2
