apiVersion: generated.federation.k8s.io/v1alpha1
kind: FederatedCustomResourceDefinition
metadata:
  name: apikeys.config.istio.io
  labels:
    app: mixer
    package: apikey
    istio: mixer-instance
spec:
  template:
    spec:
      group: config.istio.io
      names:
        kind: apikey
        plural: apikeys
        singular: apikey
      scope: Namespaced
      version: v1alpha2
