apiVersion: generated.federation.k8s.io/v1alpha1
kind: FederatedService
metadata:
  name: reportnothings.config.istio.io
  labels:
    app: mixer
    package: reportnothing
    istio: mixer-instance
spec:
  template:
    spec:
      group: config.istio.io
      names:
        kind: reportnothing
        plural: reportnothings
        singular: reportnothing
      scope: Namespaced
      version: v1alpha2
