apiVersion: generated.federation.k8s.io/v1alpha1
kind: FederatedService
metadata:
  name: opas.config.istio.io
  labels:
    app: mixer
    package: opa
    istio: mixer-adapter
spec:
  template:
    spec:
      group: config.istio.io
      names:
        kind: opa
        plural: opas
        singular: opa
      scope: Namespaced
      version: v1alpha2
