apiVersion: generated.federation.k8s.io/v1alpha1
kind: FederatedCustomResourceDefinitionPlacement
metadata:
  name: httpapispecbindings.config.istio.io
spec:
  clusterNames:
  - cluster2
  - cluster1
