apiVersion: generated.federation.k8s.io/v1alpha1
kind: FederatedCustomResourceDefinition
metadata:
  name: policies.authentication.istio.io
spec:
  template:
    spec:
      group: authentication.istio.io
      names:
        kind: Policy
        plural: policies
        singular: policy
      scope: Namespaced
      version: v1alpha1
