apiVersion: generated.federation.k8s.io/v1alpha1
kind: FederatedCustomResourceDefinition
metadata:
  name: servicecontrols.config.istio.io
  labels:
    app: mixer
    package: servicecontrol
    istio: mixer-adapter
spec:
  template:
    spec:
      group: config.istio.io
      names:
        kind: servicecontrol
        plural: servicecontrols
        singular: servicecontrol
      scope: Namespaced
      version: v1alpha2
