apiVersion: generated.federation.k8s.io/v1alpha1
kind: FederatedCustomResourceDefinition
metadata:
  name: servicecontrolreports.config.istio.io
  labels:
    app: mixer
    package: servicecontrolreport
    istio: mixer-instance
spec:
  template:
    spec:
      group: config.istio.io
      names:
        kind: servicecontrolreport
        plural: servicecontrolreports
        singular: servicecontrolreport
      scope: Namespaced
      version: v1alpha2
