apiVersion: generated.federation.k8s.io/v1alpha1
kind: FederatedCustomResourceDefinition
metadata:
  name: serviceroles.config.istio.io
  labels:
    app: mixer
    package: istio.io.mixer
    istio: rbac
spec:
  template:
    spec:
      group: config.istio.io
      names:
        kind: ServiceRole
        plural: serviceroles
        singular: servicerole
      scope: Namespaced
      version: v1alpha2
