apiVersion: generated.federation.k8s.io/v1alpha1
kind: FederatedCustomResourceDefinitionPlacement
metadata:
  name: destinationrules.networking.istio.io
  labels:
    app: istio-pilot
spec:
  clusterNames:
  - cluster2
  - cluster1
