apiVersion: generated.federation.k8s.io/v1alpha1
kind: FederatedCustomResourceDefinition
metadata:
  name: authorizations.config.istio.io
  labels:
    app: mixer
    package: authorization
    istio: mixer-instance
spec:
  template:
    spec:
      group: config.istio.io
      names:
        kind: authorization
        plural: authorizations
        singular: authorization
      scope: Namespaced
      version: v1alpha2
