apiVersion: generated.federation.k8s.io/v1alpha1
kind: FederatedDeployment
metadata:
  name: istio-egressgateway
  namespace: istio-system
  labels:
    app: egressgateway
    chart: egressgateway-0.8.0
    release: istio
    heritage: Tiller
    istio: egressgateway
spec:
  template:
    spec:
      replicas:
      template:
        metadata:
          labels:
            istio: egressgateway
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          serviceAccountName: istio-egressgateway-service-account
          containers:
          - name: egressgateway
            image: "docker.io/istio/proxyv2:0.8.0"
            imagePullPolicy: IfNotPresent
            ports:
            - containerPort: 80
            - containerPort: 443
            args:
            - proxy
            - router
            - -v
            - "2"
            - --discoveryRefreshDelay
            - '1s' #discoveryRefreshDelay
            - --drainDuration
            - '45s' #drainDuration
            - --parentShutdownDuration
            - '1m0s' #parentShutdownDuration
            - --connectTimeout
            - '10s' #connectTimeout
            - --serviceCluster
            - istio-egressgateway
            - --zipkinAddress
            - zipkin:9411
            - --statsdUdpAddress
            - istio-statsd-prom-bridge:9125
            - --proxyAdminPort
            - "15000"
            - --controlPlaneAuthPolicy
            - NONE
            - --discoveryAddress
            - istio-pilot:8080
            resources:
              {}
            env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: INSTANCE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: ISTIO_META_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            volumeMounts:
            - name: istio-certs
              mountPath: /etc/certs
              readOnly: true
          volumes:
          - name: istio-certs
            secret:
              secretName: "istio.default"
              optional: true
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: beta.kubernetes.io/arch
                    operator: In
                    values:
                    - amd64
                    - ppc64le
                    - s390x
              preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 2
                preference:
                  matchExpressions:
                  - key: beta.kubernetes.io/arch
                    operator: In
                    values:
                    - amd64
              - weight: 2
                preference:
                  matchExpressions:
                  - key: beta.kubernetes.io/arch
                    operator: In
                    values:
                    - ppc64le
              - weight: 2
                preference:
                  matchExpressions:
                  - key: beta.kubernetes.io/arch
                    operator: In
                    values:
                    - s390x
