apiVersion: core.federation.k8s.io/v1alpha1
kind: FederatedService
metadata:
  name: istio-ingress
  namespace: istio-system
  labels:
    chart: ingress-0.8.0
    release: istio
    heritage: Tiller
    istio: ingress
spec:
  template:
    spec:
      type: LoadBalancer
      selector:
        istio: ingress
      ports:
      - name: http
        nodePort: 32000
        port: 80
      - name: https
        port: 443
