apiVersion: core.federation.k8s.io/v1alpha1
kind: FederatedServicePlacement
metadata:
  name: istio-statsd-prom-bridge
  namespace: istio-system
  labels:
    chart: mixer-0.8.0
    release: istio
    istio: statsd-prom-bridge
spec:
  clusternames:
  - cluster2
  - cluster1
