apiVersion: core.federation.k8s.io/v1alpha1
kind: FederatedService
metadata:
  name: prometheus
  namespace: istio-system
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    name: prometheus
spec:
  template:
    spec:
      selector:
        app: prometheus
      ports:
      - name: http-prometheus
        protocol: TCP
        port: 9090
