apiVersion: core.federation.k8s.io/v1alpha1
kind: FederatedServicePlacement
metadata:
  # we use the normal name here (e.g. 'prometheus')
  # as grafana is configured to use this as a data source
  name: istio-citadel
  namespace: istio-system
  labels:
    app: istio-citadel
spec:
  clusternames:
  - cluster2
  - cluster1
