apiVersion: core.federation.k8s.io/v1alpha1
kind: FederatedJob
metadata:
  name: istio-cleanup-old-ca
  namespace: istio-system
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded
  labels:
    app: security
    chart: security-0.8.0
    release: istio
    heritage: Tiller
spec:
  template:
    spec:
      template:
        metadata:
          name: istio-cleanup-old-ca
          labels:
            app: security
            release: istio
        spec:
          serviceAccountName: istio-cleanup-old-ca-service-account
          containers:
          - name: hyperkube
            image: "quay.io/coreos/hyperkube:v1.7.6_coreos.0"
            command:
            - /bin/bash
            - -c
            - >
              NS="-n istio-system";
              ./kubectl get deploy istio-ca $NS;
              if [[ $? = 0 ]]; then ./kubectl delete deploy istio-ca $NS; fi;
              ./kubectl get serviceaccount istio-ca-service-account $NS;
              if [[ $? = 0 ]]; then ./kubectl delete serviceaccount istio-ca-service-account $NS; fi;
              ./kubectl get service istio-ca-ilb $NS;
              if [[ $? = 0 ]]; then ./kubectl delete service istio-ca-ilb $NS; fi
          restartPolicy: Never
