apiVersion: generated.federation.k8s.io/v1alpha1
kind: FederatedDeployment
metadata:
  name: istio-statsd-prom-bridge
  namespace: istio-system
  labels:
    chart: mixer-0.8.0
    release: istio
    istio: mixer
spec:
  template:
    spec:
      template:
        # The source istio.yaml does not specify replicas: 1 but all other Deployments do.
        # Federating this Deployment without replicas causes the target resource to never get created.
        replicas: 1
        metadata:
          labels:
            istio: statsd-prom-bridge
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          serviceAccountName: istio-mixer-service-account
          volumes:
          - name: config-volume
            configMap:
              name: istio-statsd-prom-bridge
          containers:
          - name: statsd-prom-bridge
            # The source istio.yaml specifies uses the latest image tag. This causes failure in federated or
            # non-federated installations due to the following error:
            # statsd_exporter: error: unknown short flag '-s', try --help
            image: "prom/statsd-exporter:v0.6.0"
            imagePullPolicy: IfNotPresent
            ports:
            - containerPort: 9102
            - containerPort: 9125
              protocol: UDP
            args:
            - '-statsd.mapping-config=/etc/statsd/mapping.conf'
            resources:
              {}

            volumeMounts:
            - name: config-volume
              mountPath: /etc/statsd
