apiVersion: core.federation.k8s.io/v1alpha1
kind: FederatedService
metadata:
  name: test-service
  #namespace: test-namespace
spec:
  template:
    #metadata: # uncomment if using --source service for ext-dns
    #  annotations:
    #    external-dns.alpha.kubernetes.io/hostname: svc.external.daneyon.com.
    spec:
      selector:
        app: nginx
      type: LoadBalancer
      ports:
        - name: http
          port: 80
