apiVersion: v1
kind: List
items:
- apiVersion: core.federation.k8s.io/v1alpha1
  kind: FederatedConfigMap
  metadata:
    name: istio-grafana-custom-resources
    namespace: istio-system
    labels:
      app: istio-grafana
      chart: grafana-0.1.0
      release: RELEASE-NAME
      heritage: Tiller
      istio: grafana
  spec:
    template:
      data:
        custom-resources.yaml: |-    
          apiVersion: authentication.istio.io/v1alpha1
          kind: Policy
          metadata:
            name: grafana-ports-mtls-disabled
            namespace: istio-system
          spec:
            targets:
            - name: grafana
              ports:
              - number: 3000
        run.sh: |-    
          #!/bin/sh
          
          set -x
          
          if [ "$#" -ne "1" ]; then
              echo "first argument should be path to custom resource yaml"
              exit 1
          fi
          
          pathToResourceYAML=${1}
          
          /kubectl get validatingwebhookconfiguration istio-galley 2>/dev/null
          if [ "$?" -eq 0 ]; then
              echo "istio-galley validatingwebhookconfiguration found - waiting for istio-galley deployment to be ready"
              while true; do
                  /kubectl -n istio-system get deployment istio-galley 2>/dev/null
                  if [ "$?" -eq 0 ]; then
                      break
                  fi
                  sleep 1
              done
              /kubectl -n istio-system rollout status deployment istio-galley
              if [ "$?" -ne 0 ]; then
                  echo "istio-galley deployment rollout status check failed"
                  exit 1
              fi
              echo "istio-galley deployment ready for configuration validation"
          fi
          sleep 5
          /kubectl apply -f ${pathToResourceYAML}

