apiVersion: multiclusterdns.federation.k8s.io/v1alpha1
kind: ServiceDNSRecord
metadata:
  name: istio-ingressgateway
  namespace: istio-system 
spec:
  domainRef: istio-ingressgateway
  dnsPrefix: productpage
  recordTTL: 300
  allowServiceWithoutEndpoints: false
