apiVersion: core.federation.k8s.io/v1alpha1
kind: FederatedDeploymentPlacement
metadata:
  name: istio-sidecar-injector
  namespace: istio-system
  labels:
    app: sidecarInjectorWebhook
    chart: sidecarInjectorWebhook-0.8.0
    release: istio
    heritage: Tiller
    istio: sidecar-injector
spec:
  clusterNames:
  - cluster2
  - cluster1
