apiVersion: core.federation.k8s.io/v1alpha1
kind: FederatedDeployment
metadata:
  name: istio-statsd-prom-bridge
  namespace: istio-system
  labels:
    chart: mixer-0.8.0
    release: istio
    istio: mixer
  spec:
    template:
      spec:
        template:
          metadata:
            labels:
              istio: statsd-prom-bridge
            annotations:
              sidecar.istio.io/inject: "false"
          spec:
            serviceAccountName: istio-mixer-service-account
            volumes:
            - name: config-volume
              configMap:
                name: istio-statsd-prom-bridge
            containers:
            - name: statsd-prom-bridge
              image: "prom/statsd-exporter:latest"
              imagePullPolicy: IfNotPresent
              ports:
              - containerPort: 9102
              - containerPort: 9125
                protocol: UDP
              args:
              - '-statsd.mapping-config=/etc/statsd/mapping.conf'
              resources:
                {}

              volumeMounts:
              - name: config-volume
                mountPath: /etc/statsd
