apiVersion: generated.federation.k8s.io/v1alpha1
kind: FederatedMutatingWebhookConfigurationPlacement
metadata:
  name: istio-sidecar-injector
  namespace: istio-system
  labels:
    app: istio-sidecar-injector
    chart: sidecarInjectorWebhook-0.8.0
    release: istio
    heritage: Tiller
spec:
  clusterNames:
  - cluster2
  - cluster1
