apiVersion: generated.federation.k8s.io/v1alpha1
kind: FederatedClusterRoleBinding
metadata:
 name: istio-ingress-istio-system
spec:
 template:
   roleRef:
     apiGroup: rbac.authorization.k8s.io
     kind: ClusterRole
     name: istio-pilot-istio-system
   subjects:
   - kind: ServiceAccount
     name: istio-ingress-service-account
     namespace: istio-system
