apiVersion: core.federation.k8s.io/v1alpha1
kind: FederatedServiceAccountPlacement
metadata:
  name: istio-sidecar-injector-service-account
  namespace: istio-system
  labels:
    app: istio-sidecar-injector
    chart: sidecarInjectorWebhook-0.8.0
    heritage: Tiller
    release: istio
spec:
  clusterNames:
  - cluster2
  - cluster1
