apiVersion: core.federation.k8s.io/v1alpha1
kind: FederatedServiceAccount
metadata:
  name: istio-pilot-service-account
  namespace: istio-system
  labels:
    app: istio-pilot
    chart: pilot-0.8.0
    heritage: Tiller
    release: istio
