apiVersion: core.federation.k8s.io/v1alpha1
kind: FederatedServicePlacement
metadata:
  name: istio-egressgateway-service-account
  namespace: istio-system
  labels:
    app: egressgateway
    chart: egressgateway-0.8.0
    heritage: Tiller
    release: istio
spec:
  clusternames:
  - cluster2
  - cluster1
