apiVersion: generated.federation.k8s.io/v1alpha1
kind: FederatedHorizontalPodAutoScalerPlacement
metadata:
  name: istio-egressgateway
  namespace: istio-system
spec:
  clusterNames:
  - cluster2
  - cluster1
