apiVersion: generated.federation.k8s.io/v1alpha1
kind: FederatedHorizontalPodAutoscaler
metadata:
  name: istio-ingressgateway
  namespace: istio-system
spec:
  template:
    spec:
      maxReplicas: 1
      minReplicas: 1
      scaleTargetRef:
        apiVersion: apps/v1beta1
        kind: Deployment
        name: istio-ingressgateway
      metrics:
      - type: Resource
        resource:
          name: cpu
          targetAverageUtilization: 80
