apiVersion: core.federation.k8s.io/v1alpha1
kind: FederatedJob
metadata:
  name: istio-mixer-post-install
  namespace: istio-system
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": before-hook-creation
  labels:
    app: mixer
    chart: mixer-0.8.0
    release: istio
    heritage: Tiller
spec:
  template:
    spec:
      template:
        metadata:
          name: istio-mixer-post-install
          labels:
            app: mixer
            release: istio
        spec:
          serviceAccountName: istio-mixer-post-install-account
          containers:
          - name: hyperkube
            image: "quay.io/coreos/hyperkube:v1.7.6_coreos.0"
            command:
            - ./kubectl
            - apply
            - -f
            - /tmp/mixer/custom-resources.yaml
            volumeMounts:
            - mountPath: "/tmp/mixer"
              name: tmp-configmap-mixer
          volumes:
          - name: tmp-configmap-mixer
            configMap:
              name: istio-mixer-custom-resources
          restartPolicy: Never # CRD might take some time till they are available to consume
