apiVersion: core.federation.k8s.io/v1alpha1
kind: FederatedConfigMapPlacement
metadata:
  name: istio-grafana-custom-resources
  namespace: istio-system
spec:
  clusterNames:
  - cluster1
  - cluster2
