apiVersion: core.federation.k8s.io/v1alpha1
kind: FederatedServiceAccountPlacement
metadata:
  name: istio-mixer-service-account
  namespace: istio-system
  labels:
    app: mixer
    chart: mixer-0.8.0
    heritage: Tiller
    release: istio
spec:
  clusterNames:
  - cluster2
  - cluster1
